### ISSUE TITLE
May 22nd & 23rd throughput

### ISSUE THREAD

**Issue by vincentmultari** [mikelor/TsaThroughput#14]
Hi Mike hope you're well.

I don't see data for the 22nd or 23rd of May 2022.
I apologize in advance if this is just on my end.

Thank you,
Vincent

**Comment by mikelor** [comment]
Hi Vincent,
I'll take a look and update this issue. I've found a few issues with the Azure Form Recognizer and some inconsistencies in the way that the TSA publishes their PDF files.

Glad to hear someone is checking the data!
-=mike

**Comment by mikelor** [comment]
@vincentmultari it looks like the TSA report for the period [May 15th, 2022 to May 23rd, 2022](https://www.tsa.gov/sites/default/files/foia-readingroom/tsa-throughput-data-may-15-2022-to-may-23-2022.pdf) omits data from May 22nd and May 23rd. It ends at page 986 with data through the 23:00 Hour on May 21st. (See screenshot below).

I have emailed the TSA and requested they republish the data. I've had to email them in the past, and although I never received a response, data always seems to get corrected.

I'll keep this issue open for a bit. If this does not get updated in 2 weeks feel free to bump it again as a reminder to me.

Thanks for submitting the issue.
-=mike


![image](https://user-images.githubusercontent.com/341942/172403950-960675e6-f350-4c8f-a8c9-4bcdbd11a54e.png)

**Comment by mikelor** [comment]
It turns out, it's worse than I thought. I've sent a follow up note.

After further research it looks like the data in the file is for the correct interval (all prior files have been for 7 days)

For example –
•	May 8, 2022 to May 14, 2022

The title of the May 15th file is incorrect. It should be
•	[TSA Throughput Data May 15th to May 21st](https://www.tsa.gov/sites/default/files/foia-readingroom/tsa-throughput-data-may-15-2022-to-may-23-2022.pdf) 

The next file skips May 22nd and May 23rd and instead is
•	[TSA Throughput Data May 24th to May 31s](https://www.tsa.gov/sites/default/files/foia-readingroom/tsa-throughput-data-may-24-2022-to-may-31-2022.pdf)t (8 Days)

This file is incomplete however, it only contains some of the data from May 30th. If you look at the last page it only shows data for Guam. ☹

Lastly the latest file overlaps the previous range starting at May 29th 
•	[TSA Throughput Data to May 29, 2022 to June 4, 2022](https://www.tsa.gov/sites/default/files/foia-readingroom/tsa-throughput-data-may-29-2022-to-june-4-2022.pdf)

This overlaps with the previous period starting on May 29th, instead of May 31st. It contains data through June 4th, but the title of the report says June 6th(???)

If possible, the best way to correct this is to re-run all the reports starting with the May 15th data. You would then generate the following files
1.	TSA Throughput Data May 15, 2022 to May 21, 2022
2.	TSA Throughput Data May 22, 2022 to May 28, 2022
3.	TSA Throughput Data May 29, 2022 to June 04, 2022

See the snapshot below. Thank you for reading. Please let me know if I can clarify any of the above.

**Comment by vincentmultari** [comment]
Hi Mike

Thank you so much for looking into this. 

I can't tell you how valuable it is to have this level of detail in such a manageable format. Does TSA really think people can use this data as a pdf with merged rows. I tried putting this into a data frame but it was impossible in R.

Thank you,
Vincent Multari

**Comment by mikelor** [comment]
Hey @vincentmultari,
Good news. The TSA has updated the files with the correct data. My last commit, deleted the old .pdf's and .json files to correspond to the correct date ranges, and the missing data is all there.

The latest files are for data through June 6th, 2022. Happy Data Wrangling!
